# Generated by Django 5.1.3 on 2024-11-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
