# Generated by Django 5.1.3 on 2024-11-13 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_player_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
